# Copyright: (c) 2020 - 2021 Seagate Technology LLC and/or its its Affiliates,
# All Rights Reserved
#
# This software is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nobase_mio_include_HEADERS +=

telemetry_mio_telemetry_parser_SOURCES = telemetry/mio_telemetry_parser.c

